spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bpams?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: tiger
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 100MB #最大请求文件的大小
      max-file-size: 20MB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘写入
mybatis:
  type-aliases-package: com.elec.demo.model
  mapper-locations: classpath:mapper/*.mapper.xml
server:
  port: 8080



